---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageDigestMirrorSet
metadata:
  name: olm-operator-idms
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/redhat-user-workloads/acm-multicluster-glo-tenant/multicluster-global-hub-operator-bundle-globalhub-1-5
    source: registry.redhat.io/multicluster-globalhub/multicluster-globalhub-operator-bundle
