name: Auto-merge Automated Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *" # Runs daily at 04:00 UTC (2 hours after tekton bundle update)

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get PRs with automated-update label
        id: get_prs
        run: |
          # Get all open PRs with automated-update label
          # Check that PR is mergeable and all non-tide checks are successful
          prs=$(gh pr list --label "automated-update" --state open --json number,title,url,statusCheckRollup,mergeable --jq '
            .[] | select(
              .mergeable == "MERGEABLE" and
              (.statusCheckRollup | map(select(.context != "tide" and .name != "tide")) | map(select(.state == "FAILURE" or .conclusion == "FAILURE")) | length == 0) and
              (.statusCheckRollup | map(select(.context != "tide" and .name != "tide")) | map(select(.state == "SUCCESS" or .conclusion == "SUCCESS")) | length > 0)
            )')

          if [ -z "$prs" ]; then
            echo "No PRs ready for auto-merge"
            echo "ready_prs=[]" >> $GITHUB_OUTPUT
          else
            echo "Found PRs ready for auto-merge:"
            echo "$prs" | jq -r '.number'
            echo "ready_prs<<EOF" >> $GITHUB_OUTPUT
            echo "$prs" | jq -s '.' >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Auto-merge ready PRs
        if: steps.get_prs.outputs.ready_prs != '[]'
        run: |
          ready_prs='${{ steps.get_prs.outputs.ready_prs }}'

          echo "Processing PRs for auto-merge..."
          echo "$ready_prs" | jq -r '.[] | .number' | while read pr_number; do
            echo "Processing PR #$pr_number"

            # Get PR details
            pr_info=$(echo "$ready_prs" | jq -r ".[] | select(.number == $pr_number)")
            pr_title=$(echo "$pr_info" | jq -r '.title')
            pr_url=$(echo "$pr_info" | jq -r '.url')

            echo "Attempting to merge PR #$pr_number: $pr_title"

            # Attempt to merge the PR
            if gh pr merge "$pr_number" --squash --delete-branch; then
              echo "✅ Successfully merged PR #$pr_number"

              # Optional: Add a comment to indicate auto-merge
              gh pr comment "$pr_number" --body "🤖 This PR was automatically merged because all checks passed and it has the \`automated-update\` label."
            else
              echo "❌ Failed to merge PR #$pr_number"

              # Optional: Add a comment about the failure
              gh pr comment "$pr_number" --body "🤖 Auto-merge failed for this PR. Please check for conflicts or other issues."
            fi

            echo "---"
          done
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Summary
        run: |
          echo "Auto-merge workflow completed"
          echo "Checked for PRs with 'automated-update' label that have:"
          echo "- All status checks passing (SUCCESS)"
          echo "- Mergeable state (no conflicts)"
