name: Update Tekton Task Bundles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 02:00 UTC

jobs:
  update-tekton-task-bundles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo jq
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Run update-tekton-task-bundles.sh
        id: update_bundles
        run: |
          bash ./update-tekton-task-bundles.sh pipelines/common.yaml > migration_data.json

      - name: Fail if migration is required
        run: |
          if jq -e 'length > 0' migration_data.json; then
            echo "Migration required. Please review and migrate before proceeding."
            cat migration_data.json
            exit 1
          fi

      - name: Check if common.yaml changed
        id: check_diff
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if git diff --quiet pipelines/common.yaml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request if needed
        if: steps.check_diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Tekton Task Bundles in common.yaml"
          title: "chore: update Tekton Task Bundles in common.yaml"
          body: "Automated PR to update Tekton Task Bundles. No migration required."
          branch: tekton-bundle-update
          base: main
          add-paths: pipelines/common.yaml
