name: Update Tekton Task Bundles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 02:00 UTC

jobs:
  update-tekton-task-bundles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Run update-tekton-task-bundles.sh
        id: update_bundles
        run: |
          bash ./update-tekton-task-bundles.sh pipelines/common.yaml > migration_output.txt
          # Extract migration_data JSON array
          MIGRATION_JSON=$(awk '/^\[/{flag=1} flag; /\]/{flag=0}' migration_output.txt | tr -d '\n')
          echo "migration_data=$MIGRATION_JSON" >> $GITHUB_OUTPUT

      - name: Fail if migration is required
        if: ${{ steps.update_bundles.outputs.migration_data != '' }}
        run: |
          echo "Migration required. Please review and migrate before proceeding."
          exit 1
