name: Update Tekton Task Bundles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 02:00 UTC

jobs:
  update-tekton-task-bundles:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pipeline_file:
          - common.yaml
          - common_mce_2.10.yaml
          - common-fbc.yaml
          - common-oci-ta.yaml
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo jq
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Run update-tekton-task-bundles.sh
        id: update_bundles
        run: |
          bash ./update-tekton-task-bundles.sh pipelines/${{ matrix.pipeline_file }} > migration_data.json

      - name: Check if migration is required
        id: check_migration
        run: |
          if jq -e 'length > 0' migration_data.json; then
            echo "migration_required=true" >> $GITHUB_OUTPUT

            # Format migration data for issue body
            migration_count=$(jq 'length' migration_data.json)
            migration_details=$(jq -r '.[] | "- **\(.depName)**: \(.currentValue) → \(.newValue)\n  - Link: \(.link)\n  - Package File: \(.packageFile)"' migration_data.json)

            # Create issue body with proper formatting and set as output
            echo "issue_body<<EOF" >> $GITHUB_OUTPUT
            echo "## Tekton Task Bundle Migration Required" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "The automated Tekton task bundle update process has detected that **${migration_count}** task bundle(s) require migration to newer versions in **${{ matrix.pipeline_file }}**." >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "### Migration Details:" >> $GITHUB_OUTPUT
            echo -e "$migration_details" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "### Action Required:" >> $GITHUB_OUTPUT
            echo "Please review the migration details above and manually update the task bundles. The automated update process has been halted to prevent potential breaking changes." >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "### Migration Data (JSON):" >> $GITHUB_OUTPUT
            echo '```json' >> $GITHUB_OUTPUT
            cat migration_data.json | jq . >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "### Next Steps:" >> $GITHUB_OUTPUT
            echo "1. Review the changes required for each task bundle" >> $GITHUB_OUTPUT
            echo "2. Test the new versions in a development environment" >> $GITHUB_OUTPUT
            echo "3. Manually update the task bundle references" >> $GITHUB_OUTPUT
            echo "4. Close this issue once migration is complete" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "migration_required=false" >> $GITHUB_OUTPUT
          fi

      - name: Create issue for migration
        if: steps.check_migration.outputs.migration_required == 'true'
        uses: imjohnbo/issue-bot@v3
        with:
          token: ${{ github.token }}
          title: "Tekton Task Bundle Migration Required - ${{ matrix.pipeline_file }} - ${{ github.run_id }}"
          body: ${{ steps.check_migration.outputs.issue_body }}
          labels: "migration"
          assignees: ${{ github.actor }}

      - name: Fail if migration is required
        run: |
          if jq -e 'length > 0' migration_data.json; then
            echo "Migration required for ${{ matrix.pipeline_file }}. Please review and migrate before proceeding."
            cat migration_data.json
            exit 1
          fi

      - name: Check if pipeline file changed
        id: check_diff
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if git diff --quiet pipelines/${{ matrix.pipeline_file }}; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request if needed
        if: steps.check_diff.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update Tekton Task Bundles in ${{ matrix.pipeline_file }}"
          title: "chore: update Tekton Task Bundles in ${{ matrix.pipeline_file }}"
          body: "Automated PR to update Tekton Task Bundles in ${{ matrix.pipeline_file }}. No migration required."
          branch: tekton-bundle-update-${{ matrix.pipeline_file }}
          base: main
          add-paths: pipelines/${{ matrix.pipeline_file }}
          labels: |
            automated-update
